networks:
  regnet:
    driver: bridge
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "443:8443"
    volumes:
      - /home/jj/docker/jjbasic/xaudio/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/jj/docker/jjbasic/xaudio/certs:/etc/nginx/certs:ro
    depends_on:
      - registry
    networks:
      - regnet
  xaudio:
    image: xaudio:2025.05   # 用已构建好的镜像，不自动build
    networks:
      - regnet
    restart: always
    expose:
      - "80"
    ports:
      - "80:8000"
    volumes:
      - ./audio_data:/audio           # 采集/测试音频目录
      - ./train_data:/app/train_data  # 训练数据目录
      - ./hotwords.txt:/app/hotwords.txt  # 热词表
      - ./train_texts.txt:/app/train_texts.txt  # 训练文本
      - ./custom_collect.html:/app/custom_collect.html  # 挂载前端页面
      - ./index.html:/app/index.html  # 挂载首页
    command: ["python3", "-m", "uvicorn", "infer:app", "--host", "0.0.0.0", "--port", "8000"]
# 说明：
# 1. 请将 hotwords.txt、train_texts.txt、train_data/ 目录等个性化文件放在主机当前目录下。
# 2. 容器内工作目录假设为 /app（如有不同请调整路径）。
# 3. 你可以随时在主机上编辑这些文件，容器内会实时同步。
# 如需重新构建镜像，请先手动 docker build -t xaudio:2025.05 .